package skia

/*
#include "skia.h"
*/
import "C"

type skColortype = C.sk_colortype_t
type SkColortype = skColortype

const (
	SK_COLORTYPE_UNKNOW        = C.UNKNOWN_SK_COLORTYPE
	SK_COLORTYPE_ALPHA_8       = C.ALPHA_8_SK_COLORTYPE
	SK_COLORTYPE_RGB_565       = C.RGB_565_SK_COLORTYPE
	SK_COLORTYPE_ARGB_4444     = C.ARGB_4444_SK_COLORTYPE
	SK_COLORTYPE_RGBA_8888     = C.RGBA_8888_SK_COLORTYPE
	SK_COLORTYPE_RGB_888X      = C.RGB_888X_SK_COLORTYPE
	SK_COLORTYPE_BGRA_8888     = C.BGRA_8888_SK_COLORTYPE
	SK_COLORTYPE_RGBA_1010102  = C.RGBA_1010102_SK_COLORTYPE
	SK_COLORTYPE_RGB_101010X   = C.RGB_101010X_SK_COLORTYPE
	SK_COLORTYPE_GRAY_8        = C.GRAY_8_SK_COLORTYPE
	SK_COLORTYPE_RGBA_F16_NORM = C.RGBA_F16_NORM_SK_COLORTYPE
	SK_COLORTYPE_RGBA_F16      = C.RGBA_F16_SK_COLORTYPE
	SK_COLORTYPE_RGBA_F32      = C.RGBA_F32_SK_COLORTYPE

	SK_COLORTYPE_R8G8_UNORM         = C.R8G8_UNORM_SK_COLORTYPE
	SK_COLORTYPE_A16_FLOAT          = C.A16_FLOAT_SK_COLORTYPE
	SK_COLORTYPE_R16G16_FLOAT       = C.R16G16_FLOAT_SK_COLORTYPE
	SK_COLORTYPE_A16_UNORM          = C.A16_UNORM_SK_COLORTYPE
	SK_COLORTYPE_R16G16_UNORM       = C.R16G16_UNORM_SK_COLORTYPE
	SK_COLORTYPE_R16G16B16A16_UNORM = C.R16G16B16A16_UNORM_SK_COLORTYPE
)

func Default8888Colortype() SkColortype {
	return C.sk_colortype_get_default_8888()
}
